### ISSUE TITLE
有04文件吗？

### ISSUE THREAD

**Issue by renshenga** [ChuanyuXue/The-Purchase-and-Redemption-Forecast-Challenge-baseline#1]
最近在学习关于时间序列预测的内容，知乎看到您关于这方面的评论发现您的代码思路有很多我需要学习的地方，想问一下关于04文件是有吗？  06文件需要一个feature0522.csv文件是没有的，是在04文件中吗？

**Comment by ChuanyuXue** [comment]
Hi,
There is no file04 because the methods we tried in this file worked terrible. The lack of this file won't impede the whole process.
File named feature0522.csv can be created by script 05.特征工程.ipynb.

**Comment by renshenga** [comment]
Thank you. I will study the content of the code in detail. Thank you very much for your reply.
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Chuanyu Xue"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月30日(星期三) 上午9:21
收件人:&nbsp;"ChuanyuXue/The-Purchase-and-Redemption-Forecast-Challenge-baseline"<The-Purchase-and-Redemption-Forecast-Challenge-baseline@noreply.github.com&gt;;
抄送:&nbsp;"世事~浮沉"<819676803@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ChuanyuXue/The-Purchase-and-Redemption-Forecast-Challenge-baseline] 有04文件吗？ (#1)




Closed #1.
